#!/bin/sh

mkdir -p /var/run/wifid/
echo $$ >/var/run/wifid/wifid.pid

wnet="wlan0"
not_associated=1
ESSID=""

#function testing if we are associated with an AP
function is_not_associated(){
	ifconfig $wnet up
	test=`iwconfig $wnet|grep "Access Point"`
	state=`echo $test |sed "s/.*Point:\ *//"|sed "s/\ *Tx-Power.*//"`
	if [ "$state" = 'Not-Associated' ];
	then
		not_associated=1
	else
		not_associated=0
	fi
}

#function scanning the APs and returning the first that has been configured
function search_AP(){
AP_list=`iwlist $wnet  scan |grep "ESSID"|sed s/ESSID:\"//|sed "s/\"//"`

for i in $AP_list;
	do
		if [ -f /etc/wpa_supplicant/networks/$i.cfg ]
		then
			ESSID=$i
			return
		fi
	done
	ESSID=""
}

#infinite loop
while [ 1 ];
do
	sleep 5
	is_not_associated
	if [ $not_associated -eq 1 ];
	then
		search_AP
		if ! [ "$ESSID" = "" ]
		then
			wifi-shell $ESSID
		fi
	fi
done
