#!/bin/sh

DEFAULT_CONFIG_FILE="/etc/wifish/wifish.conf"

mkdir -p /var/run/wifishd/
echo $$ >/var/run/wifishd/wifishd.pid

not_associated=1
ESSID=""

#function testing if we are associated with an AP
is_not_associated(){
	ifconfig $IWLAN up
	test=`iwconfig $IWLAN|grep "Access Point"`
	state=`echo $test |sed "s/.*Point:\ *//"|sed "s/\ *Tx-Power.*//"`
	if [ "$state" = 'Not-Associated' ];
	then
		not_associated=1
	else
		not_associated=0
	fi
}

#function scanning the APs and returning the first that has been configured
search_AP(){
AP_list=`iwlist $IWLAN scan |grep "ESSID"|sed s/ESSID:\"//|sed "s/\"//"`

for i in $AP_list;
	do
		if [ -f $USER_NETWORK_DIR/$i.cfg ]
		then
			ESSID=$i
			return
		fi
	done
	ESSID=""
}

. $DEFAULT_CONFIG_FILE

#infinite loop
while [ 1 ];
do
	sleep 5
	is_not_associated
	if [ $not_associated -eq 1 ];
	then
		search_AP
		if ! [ "$ESSID" = "" ]
		then
			wifish-cfg -n $ESSID
		fi
	fi
done
